#!/bin/sh
# usage:	diesel [options] <source>.d
#
# the following options are recognized:
#
# -a		Print AST to stdout at compile time.
# -b		Do not generate a binary executable file.
# -c		Do not perform type checking.
# -d		Turn on bison debugging (to stdout). Spammy but detailed.
# -f            Do not optimize. 
# -o <outfile>	Place the executable in <outfile> rather than `a.out'
# -p		Do not generate quads, stop after type checking.
# -q		Print quad lists to stdout at compile time. Pointless if
#		the -p flag was given.
# -s		Do not generate assembler code, stop after quads.
# -t		Include quad trace printouts in the assembler code.
# -y		Print symbol table to stdout at compile time.
# -I*, -D*, -U*	These options are passed on verbatim to the preprocessor cpp.

# Note that you can't combine several options under one -, like -abd, but
# must rather do it like -a -b -d.

# Some useful variables.
#set -e
as=/usr/ccs/bin/as
cc=/sw/gcc-3.4.6/bin/gcc
#cc=/sw/lang-5.1/opt/SUNWspro/bin/cc
cpp=/usr/ccs/lib/cpp
cppopts=
debug_flag=
print_symtab_flag=
print_ast_flag=
print_quads_flag=
no_typecheck_flag=
no_optimized_ast_flag=
no_quads_flag=
no_assembler_flag=
no_binary_flag=
output=a.out
source=0
tmpdoto=/tmp/diesel$$.o
trace_flag=


# Parse command line arguments.
while [ $# -gt 0 ]; do
    case "$1" in
        -a)     print_ast_flag="-a"
		;;
        -b)     no_binary_flag=1
		;;
        -c)     no_typecheck_flag="-c"
		;;
	-d)	debug_flag="-d"
		;;
	-f)	no_optimized_ast_flag="-f"
		;;
	-o)	shift
		if [ -z "$1" ]; then
			echo missing argument for -o
			exit 1
		fi
		output="$1"
		;;
	-p)	no_quads_flag="-p"
		;;
	-q)	print_quads_flag="-q"
		;;
	-s)	no_assembler_flag="-s"
		;;
	-t)	trace_flag="-t"
		;;
	-y)	print_symtab_flag="-y"
		;;
	-I*)	cppopts="$cppopts $1"
		;;
	-D*)	cppopts="$cppopts $1"
		;;
	-U*)	cppopts="$cppopts $1"
		;;
	-*)	echo Illegal argument "$1"
		exit 1
		;;
	*.d)	source="$1"
		;;
	esac
	shift
done

# Make sure there's a source file.
if [ ! -f $source ]; then
	echo "No source file."
	exit 1
fi

# Try to compile. Note that most arguments are passed on as is to the
# compiler (see main.cc)

$cpp -C -P $source | ./compiler $print_symtab_flag $print_ast_flag $debug_flag $no_typecheck_flag $no_optimized_ast_flag $no_quads_flag $print_quads_flag $no_assembler_flag $trace_flag

if [ $? -ne 0 ]; then
	exit $?
fi

# If we don't want a binary executable, we stop here.
if [ -n "$no_binary_flag" ]; then
	exit 0
fi

# Provided a d.out file was generated, assemble and link it.
if [ -f d.out ]; then
	$as -P d.out -o $tmpdoto
	$cc -o $output $tmpdoto diesel_rts.o $tracelib
#	$cc -o $output $tmpdoto 
	/bin/rm -f $tmpdoto
else
	echo "Compilation aborted."
	exit 1
fi
exit 0
